package com.jobcopilot.profile_service.enums;

public enum Domain {
  TECHNOLOGY,
  FINANCE,
  HEALTHCARE,
  EDUCATION,
  MARKETING,
  SALES,
  ENGINEERING,
  LEGAL,
  HUMAN_RESOURCES,
  OPERATIONS,
  CUSTOMER_SERVICE,
  CREATIVE_ARTS,
  SCIENCE,
  CONSTRUCTION,
  RETAIL,
  HOSPITALITY,
  TRANSPORTATION,
  AGRICULTURE,
  GOVERNMENT,
  NON_PROFIT
}
